title: Type Media
description: ""
footer_text: Copyright 2021 Charlotte Ashley
header_feature_image: ../uploads/placeholder2.jpg
header_text: Typography in Print Media
header_text_color: "#ffffff"
bannerheight: 40vmax
navbarheight: 55px
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
items:
  - tab: true
    name: charlotteaashley
    siteurl: https://charlotteaashley.wordpress.com
