title: TypeMedia
description: "The blog whereby typography of print books and magazines are looked into. "
footer_text: Copyright 2021 Charlotte Ashley
header_feature_image: ../uploads/photo-1516179257071-71a54dbb4853.webp
header_text: Typography in Print Media
header_text_color: "#ffffff"
bannerheight: 40vmax
navbarheight: 55px
logo: ../uploads/screenshot-2021-10-04-at-12.35.21.png
favicon: ../uploads/favicon.ico
gridlayout: false
fixednavbar: true
upzoom: true
items:
  - tab: true
    name: My Blog
    siteurl: https://charlotteaashley.wordpress.com
