title: TypeMedia
description: "The blog whereby typography of print books and magazines are looked into. "
footer_text: Copyright 2021 Charlotte Ashley
header_feature_image: ../uploads/charisse-kenion-8zsmlyaaufg-unsplash.jpg
header_text: Typography in Print Media
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 55px
logo: ../uploads/screenshot-2021-10-04-at-12.28.32.png
favicon: ../uploads/screenshot-2021-10-04-at-12.28.32.png
gridlayout: false
fixednavbar: true
upzoom: true
items:
  - tab: true
    name: charlotteaashley
    siteurl: https://charlotteaashley.wordpress.com
